### PR TITLE
Refactoring handlers, hapi validation, and improved testing

### PR DESCRIPTION
**Pull request by ngriffiths21**
I consolidated handlers so they can be used by different routes to avoid redundancy. I also created helper functions for all db manipulation as well as utility functions for parsing. I also removed all the validation logic and replaced it with registered schemas in the routes. Hapi has a built-in validation step that will throw the appropriate 400 error for us.

Now, there are basically three independent steps:

1. Request Validation, which is handled by Hapi using registered Joi schemas
2. Parsing requests/creating success responses, which is done by the handlers
3. Manipulating the db, which is done by new helper functions

I think it makes the most sense to start by testing (3) directly. Then it's easiest to test (1) and (2) with server.inject(). Yeah, you could test handlers directly too but it's really annoying (and thus unreliable) to mock the request object.

Everything for notes and patients is done already, but physicians is not implemented yet.

### CODE REVIEW

**Comment by zbo14** [comment]
I think in the route tests you require `lib/server` which requires `lib/routes` which requires `lib/routes/physician` which requires `lib/handlers/physician` which doesn't exist..

**Comment by ngriffiths21** [comment]
Weird, I'm not sure why my version doesn't care. Anyway I'm working on physician routes now.

**Comment by zbo14** [comment]
What version of npm?

**Comment by ngriffiths21** [comment]
6.0.1.

Anyway I'm making a new PR with physician routes

**Pull request closed without merging**
